# Generated by Django 2.2.2 on 2019-06-29 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urls',
            name='url',
        ),
        migrations.AddField(
            model_name='urls',
            name='short_code',
            field=models.SlugField(blank=True, max_length=15, unique=True),
        ),
        migrations.AddField(
            model_name='urls',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='Creation date'),
        ),
        migrations.AddField(
            model_name='urls',
            name='url_input',
            field=models.URLField(default=123),
            preserve_default=False,
        ),
    ]
